import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import'./style.css';

const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const nav=[['⌂','Dashboard'],['◈','Learn'],['✦','Practice'],['⌁','Doubt Solver'],['◷','Planner'],['◒','Progress']];

function App(){
 const[tab,setTab]=useState('Dashboard');
 const[data,setData]=useState(null);
 const[busy,setBusy]=useState(false);
 const[toast,setToast]=useState('');
 const[subject,setSubject]=useState('Mathematics');
 const[topic,setTopic]=useState('Conditional Probability');
 const[level,setLevel]=useState('Beginner');
 const[message,setMessage]=useState('Explain this concept with a simple example and then give me a quick check question.');
 const[answer,setAnswer]=useState('');
 const[questions,setQuestions]=useState([]);
 const[qIndex,setQIndex]=useState(0);
 const[quizScore,setQuizScore]=useState(0);
 const[quizDone,setQuizDone]=useState(false);
 const[plan,setPlan]=useState({subject:'Mathematics',date:'2026-10-15',hours:2,weak:'Conditional Probability'});
 const[file,setFile]=useState(null);

 async function getState(){try{const r=await fetch(API+'/api/state');const d=await r.json();setData(d)}catch{setToast('Backend not connected')}}
 useEffect(()=>{getState()},[]);
 async function post(path,body){setBusy(true);try{const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error();return await r.json()}catch{setToast('Start the FastAPI backend on port 8000.')}finally{setBusy(false)}}
 async function tutor(){const d=await post('/api/tutor',{message,level,subject,topic});if(d)setAnswer(d.answer)}
 async function generateQuiz(){const d=await post('/api/quiz',{subject,topic,difficulty:'Adaptive',count:5});if(d){setQuestions(d.questions);setQIndex(0);setQuizScore(0);setQuizDone(false)}}
 async function choose(i){const q=questions[qIndex];const correct=i===q.answer;if(correct)setQuizScore(s=>s+1);if(qIndex+1<questions.length)setQIndex(i2=>i2+1);else{const score=Math.round(((quizScore+(correct?1:0))/questions.length)*100);setQuizDone(true);const d=await post('/api/quiz/result',{subject,topic,score,total:questions.length});if(d){setToast(`Mastery updated to ${d.new_mastery}%`);await getState()}}}
 async function makePlan(){const d=await post('/api/planner',{...plan,hours_per_day:+plan.hours,weak_topics:plan.weak});if(d)setAnswer(d.plan)}
 async function uploadDoubt(){if(!file)return;setBusy(true);const fd=new FormData();fd.append('file',file);try{const r=await fetch(API+'/api/doubt',{method:'POST',body:fd});const d=await r.json();setAnswer(d.answer+'\n\nPipeline: '+d.next_step)}catch{setToast('Could not upload image')}finally{setBusy(false)}}
 const mastery=useMemo(()=>data?.state?.subjects?.[subject]?.mastery||{},[data,subject]);
 const avg=useMemo(()=>{const a=Object.values(mastery);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0},[mastery]);
 const weak=useMemo(()=>{const a=Object.entries(mastery);return a.length?a.sort((x,y)=>x[1]-y[1])[0]:['No topic yet',0]},[mastery]);
 const strong=useMemo(()=>{const a=Object.entries(mastery);return a.length?a.sort((x,y)=>y[1]-x[1])[0]:['No topic yet',0]},[mastery]);
 function page(){
  if(tab==='Dashboard')return <Dashboard data={data} avg={avg} weak={weak} strong={strong} setTab={setTab} />;
  if(tab==='Learn')return <Learn subject={subject} setSubject={setSubject} topic={topic} setTopic={setTopic} level={level} setLevel={setLevel} message={message} setMessage={setMessage} answer={answer} busy={busy} tutor={tutor}/>;
  if(tab==='Practice')return <Practice topic={topic} setTopic={setTopic} questions={questions} qIndex={qIndex} quizScore={quizScore} quizDone={quizDone} generateQuiz={generateQuiz} choose={choose} busy={busy}/>;
  if(tab==='Doubt Solver')return <Doubt file={file} setFile={setFile} upload={uploadDoubt} answer={answer} busy={busy}/>;
  if(tab==='Planner')return <Planner plan={plan} setPlan={setPlan} makePlan={makePlan} answer={answer} busy={busy}/>;
  return <Progress data={data} subject={subject} setSubject={setSubject} mastery={mastery} avg={avg}/>;
 }
 return <div className="app"><header><div className="brand"><div className="logo">LX</div><div><b>LearnX <span>AI</span></b><small>Adaptive Learning Copilot</small></div></div><div className="header-right"><span className="live"><i/> AI engine ready</span><div className="avatar">V</div></div></header><div className="shell"><aside><div className="nav-title">WORKSPACE</div>{nav.map(([icon,label])=><button className={tab===label?'active':''} onClick={()=>{setTab(label);setAnswer('')}} key={label}><span>{icon}</span>{label}</button>)}<div className="side-card"><div className="spark">✦</div><b>Adaptive mode</b><p>LearnX uses your quiz performance to decide what you should study next.</p></div></aside><main>{page()}</main></div>{toast&&<button className="toast" onClick={()=>setToast('')}>{toast} ×</button>}</div>
}

function Top({eyebrow,title,sub,children}){return <div className="top"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{children}</div>}
function Dashboard({data,avg,weak,strong,setTab}){return <><Top eyebrow="OVERVIEW" title={`Good to see you, ${data?.state?.student?.name||'Learner'} 👋`} sub="Your learning path is adapting to your performance in real time."><select><option>Mathematics</option><option>Computer Science</option></select></Top><div className="hero"><div><div className="pill">✦ AI RECOMMENDATION</div><h2>{data?.recommendation||'Start with a diagnostic quiz to personalize your path.'}</h2><p>Based on your recent performance, LearnX has identified your next best learning action.</p><button className="primary" onClick={()=>setTab('Learn')}>Start recommended lesson →</button></div><div className="hero-ring"><strong>{avg}%</strong><span>average mastery</span></div></div><div className="stat-grid"><Stat label="Average mastery" value={`${avg}%`} note="Across tracked topics"/><Stat label="Focus topic" value={weak[0]} note={`${weak[1]}% mastery · needs attention`}/><Stat label="Strongest topic" value={strong[0]} note={`${strong[1]}% mastery · keep it fresh`}/><Stat label="Study streak" value={`${data?.state?.streak||0} days`} note="Consistency matters"/></div><div className="grid2"><div className="panel"><div className="panel-head"><div><b>Learning map</b><small>Topic mastery</small></div><button onClick={()=>setTab('Progress')}>View all</button></div><MasteryRows mastery={data?.state?.subjects?.Mathematics?.mastery||{}}/></div><div className="panel"><div className="panel-head"><div><b>Next best action</b><small>Adaptive loop</small></div></div><div className="loop"><span>1</span><div><b>Learn</b><small>Targeted explanation</small></div><em>→</em><span>2</span><div><b>Practice</b><small>Adaptive quiz</small></div><em>→</em><span>3</span><div><b>Adapt</b><small>Update mastery</small></div></div></div></div></>}
function Stat({label,value,note}){return <div className="stat"><small>{label}</small><b>{value}</b><span>{note}</span></div>}
function MasteryRows({mastery}){return <div className="rows">{Object.entries(mastery).map(([k,v])=><div className="row" key={k}><div><b>{k}</b><small>{v<50?'Needs focus':v<70?'Building':'Strong'}</small></div><div className="bar"><i style={{width:`${v}%`}}/></div><strong>{v}%</strong></div>)}</div>}
function Learn(p){return <><Top eyebrow="LEARN" title="AI Tutor" sub="Explanations adapt to your level and your current weak topic."><div className="seg">{['Beginner','Medium','Advanced'].map(x=><button className={p.level===x?'sel':''} onClick={()=>p.setLevel(x)} key={x}>{x}</button>)}</div></Top><div className="learn-grid"><div className="panel input-panel"><label>Subject</label><select value={p.subject} onChange={e=>p.setSubject(e.target.value)}><option>Mathematics</option><option>Computer Science</option></select><label>Topic</label><input value={p.topic} onChange={e=>p.setTopic(e.target.value)}/><label>What do you want to understand?</label><textarea value={p.message} onChange={e=>p.setMessage(e.target.value)}/><button className="primary wide" onClick={p.tutor} disabled={p.busy}>{p.busy?'Thinking…':'Ask LearnX ✦'}</button></div><div className="panel response"><div className="ai-label"><span>✦</span> LEARNX RESPONSE</div>{p.answer?<pre>{p.answer}</pre>:<div className="empty"><div>✦</div><b>Your personalized explanation will appear here.</b><span>Ask about a concept, example, formula, or mistake.</span></div>}</div></div></>}
function Practice(p){const q=p.questions[p.qIndex];return <><Top eyebrow="PRACTICE" title="Adaptive Quiz" sub="Difficulty is selected from your current mastery, not randomly."><button className="primary" onClick={p.generateQuiz} disabled={p.busy}>{p.busy?'Generating…':'Generate adaptive quiz'}</button></Top><div className="quiz-layout"><div className="panel"><label>Topic</label><input value={p.topic} onChange={e=>p.setTopic(e.target.value)}/>{!q&&!p.quizDone&&<div className="empty big"><div>◎</div><b>Ready for a targeted practice session?</b><span>LearnX will generate questions around your selected topic and update mastery after submission.</span></div>}{q&&!p.quizDone&&<><div className="qmeta">QUESTION {p.qIndex+1} / {p.questions.length}</div><h2>{q.question}</h2><div className="options">{q.options.map((o,i)=><button onClick={()=>p.choose(i)} key={i}><span>{String.fromCharCode(65+i)}</span>{o}</button>)}</div></>}{p.quizDone&&<div className="result"><div className="score-ring">{Math.round(p.quizScore/p.questions.length*100)}%</div><h2>Practice complete</h2><p>Your result has been fed back into the adaptive learning engine.</p><button className="primary" onClick={p.generateQuiz}>Practice again</button></div>}</div><div className="panel side-insight"><div className="pill">ADAPTIVE LOOP</div><h3>What happens after the quiz?</h3><p>LearnX blends your new score with previous mastery, so one quiz cannot suddenly distort your learning profile.</p><div className="mini-step"><b>01</b><span>Measure performance</span></div><div className="mini-step"><b>02</b><span>Update topic mastery</span></div><div className="mini-step"><b>03</b><span>Choose the next activity</span></div></div></div></>}
function Doubt(p){return <><Top eyebrow="DOUBT SOLVER" title="Ask from a photo" sub="Upload a question and LearnX can route it through OCR → concept detection → solution → practice."><span className="pill">VISION READY</span></Top><div className="doubt-grid"><div className="panel upload"><div className="drop"><div>📸</div><b>Drop your question image here</b><span>or choose a JPG, PNG or PDF</span><input type="file" accept="image/*,.pdf" onChange={e=>p.setFile(e.target.files[0])}/>{p.file&&<small>{p.file.name}</small>}</div><button className="primary wide" disabled={!p.file||p.busy} onClick={p.upload}>{p.busy?'Analyzing…':'Solve this doubt'}</button></div><div className="panel response"><div className="ai-label">✦ SOLUTION PIPELINE</div>{p.answer?<pre>{p.answer}</pre>:<div className="pipeline"><Step n="01" t="Read" s="Extract the question"/><Step n="02" t="Understand" s="Detect subject & concept"/><Step n="03" t="Solve" s="Explain step by step"/><Step n="04" t="Practice" s="Generate a similar question"/></div>}</div></div></>}
function Step({n,t,s}){return <div className="pipeline-step"><b>{n}</b><div><strong>{t}</strong><span>{s}</span></div></div>}
function Planner(p){return <><Top eyebrow="PLANNER" title="Adaptive Study Planner" sub="Build a plan around your exam date, available time and weakest topics."/><div className="planner-grid"><div className="panel input-panel"><label>Subject</label><input value={p.plan.subject} onChange={e=>p.setPlan({...p.plan,subject:e.target.value})}/><label>Exam date</label><input type="date" value={p.plan.date} onChange={e=>p.setPlan({...p.plan,date:e.target.value})}/><label>Hours per day</label><input type="number" min="0.5" step="0.5" value={p.plan.hours} onChange={e=>p.setPlan({...p.plan,hours:e.target.value})}/><label>Weak topics</label><input value={p.plan.weak} onChange={e=>p.setPlan({...p.plan,weak:e.target.value})}/><button className="primary wide" onClick={p.makePlan} disabled={p.busy}>{p.busy?'Building…':'Build adaptive plan'}</button></div><div className="panel response"><div className="ai-label">◷ 7-DAY PLAN</div>{p.answer?<pre>{p.answer}</pre>:<div className="empty"><div>◷</div><b>Your plan will be generated around your constraints.</b><span>When performance changes, regenerate to rebalance weak areas.</span></div>}</div></div></>}
function Progress({data,subject,setSubject,mastery,avg}){const trend=data?.state?.subjects?.[subject]?.trend||[];return <><Top eyebrow="PROGRESS" title="Your learning intelligence" sub="See what you know, what needs attention, and how your mastery is changing."><select value={subject} onChange={e=>setSubject(e.target.value)}><option>Mathematics</option><option>Computer Science</option></select></Top><div className="stat-grid"><Stat label="Average mastery" value={`${avg}%`} note="Current learning state"/><Stat label="Study time" value={`${Math.round((data?.state?.study_minutes||0)/60)}h`} note="Tracked sessions"/><Stat label="Streak" value={`${data?.state?.streak||0}d`} note="Keep the habit"/><Stat label="Quizzes" value={data?.state?.quiz_history?.length||0} note="Recent attempts"/></div><div className="grid2"><div className="panel"><div className="panel-head"><div><b>Topic mastery</b><small>Current state</small></div></div><MasteryRows mastery={mastery}/></div><div className="panel"><div className="panel-head"><div><b>Mastery trend</b><small>Recent checkpoints</small></div></div><div className="chart">{trend.map((v,i)=><div className="barcol" key={i}><i style={{height:`${Math.max(12,v)}%`}}/><span>{v}</span></div>)}</div><div className="chart-note">Each completed quiz becomes feedback for the next learning decision.</div></div></div></>}

createRoot(document.getElementById('root')).render(<App/>);
